### ISSUE TITLE
Native app login

### ISSUE THREAD

**Issue by Maudini** [quavedev/apple-oauth#1]
The web app login works great, however the native app login isn't working. I build the application with the following: `meteor build ../output-folder --mobile-settings settings.json --server https://example.meteorapp.com`. I have specified the apple login settings in a few places:

**Settings.js**

      "apple": {
        "secret": "-----BEGIN PRIVATE KEY-----\nexample\nexample\nexample\nexample\n-----END PRIVATE KEY-----",
        "redirectUri": "https://www.example.meteorapp.com/_oauth/apple",
        "clientId": "com.example.client",
        "nativeClientId": "com.example.native",
        "teamId": "WexampleT",
        "keyId": "UexampleU",
        "scope": "name%20email",
        "responseMode": "form_post",
        "responseType": "code",
        "service": "apple"
      },

**db.meteor_accounts_loginServiceConfiguration**
The object here looks the same as the `Settings.js` (above).

In the `loginWithApple` function, I specify the scope/requestPermissions, otherwise I get a login that doesn't give the option for the user to provide their email. 

    Meteor.loginWithApple(
      {
        requestPermissions: "name%20email",
        scope: "name%20email",
      },
      function(err, res) {
        if (err) {
          throw new Meteor.Error("Apple login failed", err);
        }
      }
    );

**This is what I see when I don't specify the scope/requestPermissions** 
<img width="200" alt="IMG_592F3283D565-1" src="https://user-images.githubusercontent.com/68401715/90150508-5bc2cc00-dd4b-11ea-8be2-ab9b0d6e80b5.png">
**With the permissions I see this (better)**
<img width="200" alt="IMG_251A38487F08-2" src="https://user-images.githubusercontent.com/68401715/90150982-d55aba00-dd4b-11ea-9e6a-9e7bf0e37c34.png">

The only way that we have been able to get it working is by going into `db.meteor_accounts_loginServiceConfiguration` and changing the clientId to be the same as the nativeClientId, i.e. `"clientId":  "com.example.native",`, otherwise I am getting [the invalid_grant return](https://developer.apple.com/forums/thread/118135), signifying that the `clientId` is different from the App Id, which I thought the `nativeClientId` was supposed to handle.

**Side Note:**
I have Sign In With Apple enabled on Xcode and in my provisioning profile:
![Screen Shot 2020-08-13 at 10 04 19 AM](https://user-images.githubusercontent.com/68401715/90151478-5dd95a80-dd4c-11ea-8667-c2bd5c3cef23.png)

**Comment by renanccastro** [comment]
Hi!
Sorry it took so long to answer. I wasn't being notified about anything here.

For log in, use the following:

  Meteor.loginWithApple({
    requestPermissions: ['name', 'email'],
  });

And yes, the clientId is your Apple "Service ID", and the nativeClientId is the actual bundle id of your app.

Are you still having issues? I've updated the readme to be more clear about the process

**Comment by renanccastro** [comment]
We got no response to this for a long time, I'm closing this issue. If you still see problems, let us know.
