### ISSUE TITLE
Support for multiple redirect URIs?

### ISSUE THREAD

**Issue by derwaldgeist** [quavedev/apple-oauth#16]
Hi, I saw that the package supports multiple clientIds. Does this also work for multiple redirectURIs? We have a web app that listens to different domains, but is 1:1 the same otherwise.

**Comment by filipenevola** [comment]
hi @derwaldgeist sorry for the delay.

Please submit a PR and we will review and merge ASAP.

Feel free to ping us at oss@quave.dev

Thanks

**Comment by renanccastro-provi** [comment]
@derwaldgeist you can use multiple redirect URIs without issues, actually, that's the reason multiple service ids are supported because Apple limits the number of different redirect URIs by serviceids.
