### ISSUE TITLE
Cordova Plugin Device dependency needs updating

### ISSUE THREAD

**Issue by bslocombe** [quavedev/apple-oauth#22]
Using the latest build on 2.15, IOS cordova crashes with a CDVDevice "device" plugin not found issue. Simply updating the Cordova.depends package fixes this: 

From 
'cordova-plugin-device': '2.0.3'

To
 'cordova-plugin-device': '2.1.0'

**Comment by renanccastro** [comment]
Published quave:apple-oauth@3.1.2.
