### ISSUE TITLE
How to config the service?

### ISSUE THREAD

**Issue by derwaldgeist** [quavedev/apple-oauth#3]
It's a bit confusing that the documentation won't tell you how to apply the configuration. Is this meant to be placed in `settings.json` or inserted via `ServiceConfigurations.configurations`?

I would prefer the second approach, as it would allow me to keep the private key out of my `settings.json` and store it in a separate credentials file instead.

**Comment by renanccastro** [comment]
Yes, it is currently in the settings.json, I've updated it to say more explicitly.

**Comment by derwaldgeist** [comment]
Ah, I see. Makes sense. I wouldn't want to add my key to the settings.json

**Comment by derwaldgeist** [comment]
Another question on this: I managed to set-up the service and I can get to the point where the OAuth redirect page is being called. But the sign-in won't work due to this error being thrown on the server-side:

```
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Apple. failed [400] {"error":"invalid_client"}
```

So I am wondering if the client ID is really the service ID as stated in the docs?

**Comment by derwaldgeist** [comment]
Ok, I tried the app bundle identifier instead, but this led to an immediate error. So I guess the service ID was actually correct. But still, I am wondering why the OAuth error appears?

**Comment by derwaldgeist** [comment]
Nevermind. I used the wrong key ID.
