### ISSUE TITLE
Apple login fails on iOS 14 due to semver issue

### ISSUE THREAD

**Issue by wreiske** [quavedev/apple-oauth#4]
I'm getting an error here:
https://github.com/quavedev/apple-oauth/blob/457dce1d96c1aefff25bf6aa98f14528ba396666/apple_client.js#L100

```
TypeError: null is not an object (evaluating 'matches[1]')
```

<img width="437" alt="image" src="https://user-images.githubusercontent.com/6295044/97391942-af9a7700-189d-11eb-8edf-425f0a1bab0b.png">

It looks like it's breaking because the iOS version is reporting as 14.0. The semver-lite library doesn't support that format, and it also doesn't include the coerce found [in other libraries](https://www.npmjs.com/package/semver#coercion).

**Comment by wreiske** [comment]
@renanccastro looks like you may have touched this code last.

**Comment by renanccastro** [comment]
Hi, @wreiske . Thanks for tagging me, I wasn't being notified about issues on this repo. I'm checking.

**Comment by renanccastro** [comment]
Published as quave:apple-oauth@1.4.2
