### ISSUE TITLE
Apple login is firing off Reload._onMigrate

### ISSUE THREAD

**Issue by wreiske** [quavedev/apple-oauth#5]
For some reason when I click on the Sign in with Apple it fires off Reload._onMigrate, causing the app to reload. 

```javascript
Reload._onMigrate(function (retry) {
   console.log('Fires!');
    return [true, {}];
});
```

**Comment by renanccastro** [comment]
We are running it on production and we never saw this, unfortunately...
Do you have a simple project for reproduction? I can take a look.

**Comment by wreiske** [comment]
I will create an example later today, but it looks like this only happens in Safari.

**Comment by wreiske** [comment]
[sample-apple-migrate.tar.gz](https://github.com/quavedev/apple-oauth/files/5451941/sample-apple-migrate.tar.gz)

Here's a sample. Tested on Safari / macOS Catalina 10.15.6.

**Comment by wreiske** [comment]
Looks like the loginStyle of redirect fires off a reload migration:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/6295044/97962098-b92a5000-1d71-11eb-9bc5-63a7d82365c0.png">

**Comment by wreiske** [comment]
I ended up fixing this for my own purposes:

```
Reload._onMigrate(function (retry, immediateMigration) {
  // if immediateMigration is set, just do the reload without prompting....
  if (immediateMigration !== {}) {
    return [true, {}];
  }
});
```

**Comment by mcorbelli** [comment]
i think i have the same problem. when i use sign-in with apple in redirect mode, the page is reloaded before the login flow is completed.

where should the code be changed to prevent the page from reloading when i try to login with apple on my iphone? any example? thanks
