### ISSUE TITLE
Apple.requestCredential() signature change request

### ISSUE THREAD

**Issue by derwaldgeist** [quavedev/apple-oauth#7]
I have a working version of  `meteor-link-accounts` that supports `quave:accounts-apple`:

https://github.com/marblear/meteor-link-accounts/blob/feature/sign-in-with-apple/community-services/apple.js

However, to make it as compatible as possible, I had to make a weird workaround, since you changed the default signature of the `requestCredential()` function:

https://github.com/quavedev/apple-oauth/blob/master/apple_client.js#L13

In the other oauth packages, the `oauthCallback` comes right after the options, but here it is the `nativeCallback`.

In my own method, I swapped these, so people can pass in a native callback if they want to. If it is not available, the regular callback is being used. To make things consistent, I'd like to recommend to put the nativeCallback third in your package as well.

**Comment by renanccastro** [comment]
Hello!
Sorry for the delay!
( big delay, I know :/ )

We are still maintaining this package, and I've just changed what you asked for.

Thanks!
